services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://app:0123456789abcdef@db/app
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 0123456789abcdef